/**
 * Review-build only: patches the mock June 2026 queue so the Manager
 * reviewer task ("find and handle the one exception case; approve the
 * rest") is actually completable.
 *
 * The autogenerated seed (seedData.ts) never contains a ProcessException —
 * those only ever get added at runtime through the "Ausnahme vermerken" UI —
 * and June 2026 only has a single READY_FOR_APPROVAL record to begin with.
 * A scripted task needs the queue to already contain one exception case
 * plus a few clean ones, so that fixture data lives here instead of hand-
 * editing the autogenerated file.
 */
import type { MonthRecord } from '../../domain/types';
import { MONTH } from './seed';

/** Letzter Monat mit Daten in der Testdaten-Übersicht — folgt der Übersicht, nicht fest verdrahtet. */
export const REVIEW_TASK_MONTH = MONTH;

const CLEAN_CASES = ['PK03', 'PK06'];
const EXCEPTION_CASE = 'PK08';

export function applyReviewTaskFixture(records: MonthRecord[]): MonthRecord[] {
  return records.map((r) => {
    if (r.month !== REVIEW_TASK_MONTH) return r;

    if (r.participantId === EXCEPTION_CASE) {
      return {
        ...r,
        status: 'READY_FOR_APPROVAL',
        exceptions: [
          {
            id: 'review-fixture-exception',
            category: 'NACHWEIS',
            reason:
              'Mehrere Fehltage im Juni — Rücksprache mit TN erfolgt, Nachweise werden nachgereicht.',
            createdBy: 'u-mira',
            createdAt: '2026-06-29T09:00:00.000Z',
            visibility: 'TEAM',
            approvedByManager: false,
          },
        ],
      };
    }

    if (CLEAN_CASES.includes(r.participantId)) {
      return {
        ...r,
        status: 'READY_FOR_APPROVAL',
        exceptions: [],
        signature: { mode: 'PAPER', signedAt: '2026-06-28' },
      };
    }

    return r;
  });
}
